# Generated by Django 3.1 on 2022-06-28 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='dpi',
            field=models.PositiveIntegerField(null=True, verbose_name='DPI del Paciente'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefonoFamiliar',
            field=models.PositiveIntegerField(verbose_name='Telefono del familiar'),
        ),
    ]
