# Generated by Django 3.1 on 2022-06-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_auto_20220627_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='dpi',
            field=models.CharField(max_length=13, null=True, verbose_name='DPI del Paciente'),
        ),
    ]
