# Generated by Django 3.1 on 2022-06-28 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_entradas_tipoentrada'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSalida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTipo', models.CharField(max_length=50, verbose_name='Tipo de Salida')),
            ],
            options={
                'verbose_name': 'Tipo de salida',
                'verbose_name_plural': 'Tipos de salidas',
                'db_table': 'tipo_salida',
            },
        ),
        migrations.CreateModel(
            name='Salidas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enteDebitador', models.CharField(max_length=50, verbose_name='Ente Debitador')),
                ('descripcionSalida', models.CharField(max_length=200, verbose_name='Motivo de la salida monetaria')),
                ('tipoSalida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.tiposalida')),
            ],
            options={
                'verbose_name': 'Salida',
                'verbose_name_plural': 'Salidas',
                'db_table': 'salidas',
            },
        ),
    ]
