# Generated by Django 3.1 on 2022-06-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_medico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='nombreCompleto',
            field=models.CharField(max_length=50, verbose_name='Nombre completo del Medico'),
        ),
    ]
