# Generated by Django 3.1 on 2022-06-29 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del medicamento')),
                ('presentacion', models.CharField(max_length=50, verbose_name='Presentacion')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Precio de Venta')),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Descuento')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'db_table': 'medicamento',
            },
        ),
        migrations.CreateModel(
            name='DetalleMedicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(max_length=50, verbose_name='Codigo del lote del producto')),
                ('ubicacion', models.CharField(max_length=50, verbose_name='Ubicacion del lote')),
                ('fechavencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundacion.medicamento')),
            ],
            options={
                'verbose_name': 'Detalle del medicamento',
                'verbose_name_plural': 'Detalle de los medicamentos',
                'db_table': 'detalle_medicamento',
            },
        ),
    ]
