# Generated by Django 3.1 on 2022-06-29 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundacion', '0002_detallemedicamento_medicamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoExamen', models.CharField(max_length=100, verbose_name='Tipo de Examen')),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundacion.empleado')),
            ],
            options={
                'verbose_name': 'Laboratorio',
                'verbose_name_plural': 'Laboratorios',
                'db_table': 'laboratorio',
            },
        ),
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundacion.empleado')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundacion.medicamento')),
            ],
            options={
                'verbose_name': 'Farmacia',
                'verbose_name_plural': 'Farmacias',
                'db_table': 'farmacia',
            },
        ),
    ]
